language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 44927d483691d527e97b3ba1cde1e3e9c6290a23
  local_dir: build
  on:
    branch: master