language: node_js
language: node_js
node_js:
  - "node"

after_success:
  - git config --global user.name "jacobg1"
  - git config --global user.email "jeg4t@virginia.edu"
  - git remote rm origin
  - git remote add origin https://jacobg1:${GITHUB_TOKEN}@github.com/jacobg1/data-playground.git
  - npm run deploy