language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  - npm run deploy
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
 

 