language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  local_dir: ./build/
  target_branch: gh-pages
