dist: trusty
language: node_js
node_js:
  - "stable"
before_script:
  - npm install  
script:
  - npm test
  - npm run build
after_success: 
  - surge --project ./build --domain stock-lines.surge.sh  